name: microservices-kafka
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.115.8
      - uvicorn[standard]==0.34.0
      - aiokafka==0.12.0
      - pydantic==2.10.6
      - pydantic-settings==2.7.1
      - python-dotenv==1.0.1
      - PyJWT==2.10.1
      - bcrypt==4.2.1
      - mysql-connector-python==9.2.0
      - SQLAlchemy==2.0.38
      - alembic==1.14.1
      - redis==5.2.1
      - pytest==8.3.5
      - pytest-asyncio==0.25.3
